// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/demo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculationClient is the client API for Calculation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculationClient interface {
	CalculateValues(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationReply, error)
}

type calculationClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculationClient(cc grpc.ClientConnInterface) CalculationClient {
	return &calculationClient{cc}
}

func (c *calculationClient) CalculateValues(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationReply, error) {
	out := new(CalculationReply)
	err := c.cc.Invoke(ctx, "/proto.Calculation/CalculateValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculationServer is the server API for Calculation service.
// All implementations must embed UnimplementedCalculationServer
// for forward compatibility
type CalculationServer interface {
	CalculateValues(context.Context, *CalculationRequest) (*CalculationReply, error)
	mustEmbedUnimplementedCalculationServer()
}

// UnimplementedCalculationServer must be embedded to have forward compatible implementations.
type UnimplementedCalculationServer struct {
}

func (UnimplementedCalculationServer) CalculateValues(context.Context, *CalculationRequest) (*CalculationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateValues not implemented")
}
func (UnimplementedCalculationServer) mustEmbedUnimplementedCalculationServer() {}

// UnsafeCalculationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculationServer will
// result in compilation errors.
type UnsafeCalculationServer interface {
	mustEmbedUnimplementedCalculationServer()
}

func RegisterCalculationServer(s grpc.ServiceRegistrar, srv CalculationServer) {
	s.RegisterService(&Calculation_ServiceDesc, srv)
}

func _Calculation_CalculateValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculationServer).CalculateValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Calculation/CalculateValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculationServer).CalculateValues(ctx, req.(*CalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Calculation_ServiceDesc is the grpc.ServiceDesc for Calculation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Calculation",
	HandlerType: (*CalculationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateValues",
			Handler:    _Calculation_CalculateValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo.proto",
}
